### ISSUE TITLE
Comments count as similar code

### ISSUE THREAD

**Issue by jluchiji** [codeclimate/codeclimate-duplication#104]
In one of my projects, I have a banner comment on top of every file, which is like the following:

```js
/**
 * path/to/file.js
 *
 * @author  Author <author@website.com>
 * @license 2015-16 (C) Author. All Rights Reserved.
 */
```

for some reason the above banners in each file are marked as similar code.

**Comment by pbrisbin** [comment]
Hi @jluchiji, sorry for the trouble here.

We're having difficulty reproducing this issue ourselves. Do you mind confirming that you're on the latest version of everything?

```
codeclimate version
docker images | grep duplication
```

If on Homebrew, you can update with:

```
brew update && brew upgrade codeclimate
```

Thanks

**Comment by dblandin** [comment]
Hi @jluchiji, are you still experiencing this issue?

**Comment by dblandin** [comment]
Going to close this issue for now. Feel free to reopen if this is still an issue. Thanks!
