### ISSUE TITLE
Including/excluding files

### ISSUE THREAD

**Issue by jekuta** [codeclimate/codeclimate-duplication#113]
What is the recommended way of excluding or including files for duplication engine? I would like to exclude the `specs` folder, but only for the duplication engine analysis. 

I was actually using the undocumented `paths` option which was removed some time ago. Is there some alternative way to achieve the same result now?

**Comment by wfleming** [comment]
Hi @jekuta,

Sorry for the recent breakage of that undocumented `paths` option: it was the victim of a refactor targeting some bugs and performance issues.

Fortunately, we do support [excluding paths for specific engines](https://docs.codeclimate.com/docs/excluding-files-and-folders#section-exclude-paths-for-specific-engines): You can put an `exclude_paths` key under any any engine, and it will be applied in addition to the global `exclude_paths`. E.g.:

```yaml
engines:
  duplication:
    enabled: true
    exclude_paths:
      - spec/
```

Let me know if that doesn't work for you.

**Comment by jekuta** [comment]
@wfleming Thanks for the fast reply! It worked. I seem to have missed this option, so good to know that is the general way of excluding files for all the engines now:)
