### ISSUE TITLE
Excluding files and/or directories

### ISSUE THREAD

**Issue by Mange** [codeclimate/codeclimate-duplication#115]
Test code is sometimes marked as duplicate and/or similar, which is usually not a problem for me since I accept some duplication in tests just to get clearer and more focused expectations.

It would be helpful to be able to ignore certain files or directories from this engine so I don't get those kinds of checks done on the tests.

Is that possible?

**Comment by devinus** [comment]
Yeah, I need to ignore all my tests as they're almost always duplicated code.

**Comment by jekuta** [comment]
You can exclude files and folders for specific engines. I raised this same issue a little while ago and got an answer here. https://github.com/codeclimate/codeclimate-duplication/issues/113

**Comment by Mange** [comment]
Thanks, Laura.

Could that information be added to the documentation, perhaps?

Den ons 4 maj 2016 08:34Laura Paakkinen <notifications@github.com> skrev:

**Comment by pbrisbin** [comment]
Hi @Mange that information is present in our main documentation site:

https://docs.codeclimate.com/docs/excluding-files-and-folders#section-exclude-paths-for-specific-engines

If you have any suggestions for improving those docs (or making them easier to find), please let us know.

**Comment by Mange** [comment]
Thanks. I opened a PR with my suggested changes. :-)
