### ISSUE TITLE
Comments count as similar code, take two

### ISSUE THREAD

**Issue by TomFrost** [codeclimate/codeclimate-duplication#118]
I'm having the same issue as described in #104, however that issue's author disappeared.

I have the following banner at the top of my files, which is being flagged as duplicated code (mass = 96):

```javascript
/*
 * Embassy
 * Copyright (c) 2016, TechnologyAdvice LLC
 */
```

This is an open-source project and this issue can be found on the website here: https://codeclimate.com/github/TechnologyAdvice/Embassy/issues

It would be a shame to turn duplication checking off, or set the mass threshold to 97, but there's no other obvious solution at the moment.

**Comment by pbrisbin** [comment]
Hey @TomFrost sorry for the delayed response here. I think perhaps this isn't a case of the documentation comments being flagged as duplication, but some bad luck in how the UI works.

We truncate issues for display on the website. In truncated form, it likes like exactly and only the documentation is being flagged, but the duplication being reported is actually the whole module (not just the comment), lines 1-23. If you expand via the View More link, you can see:

![](https://files.pbrisbin.com/screenshots/desktop_160625200126.png)

I'm inclined to agree with the engine, those modules do look extremely similar. In this case, these boilerplatey error classes might be best written this way, so I might try excluding those files from the duplication engine. That way you don't have to turn off the engine entirely or use a high threshold.

**Comment by dblandin** [comment]
Sounds like this is a UI concern and not a problem with the engine so I'm going to go ahead and close this issue.

Thanks for the report!
