### ISSUE TITLE
[Question] - Any plans for including TypeScript?

### ISSUE THREAD

**Issue by dsifford** [codeclimate/codeclimate-duplication#119]
Hi there,

Totally love this. Any plans for supporting typescript analysis in the future?

Thanks! 👍

**Comment by pbrisbin** [comment]
Hey @dsifford we don't have any concrete plans to add TypeScript support to our duplication engine at this time -- however PRs are always welcome :)

We do have a typescript specific [engine](https://github.com/tkqubo/codeclimate-tslint) that wraps the `tslint` tool, though it doesn't look it does the sort of structural duplication check you'd find in our duplication engine.
