### ISSUE TITLE
(CC::Analyzer::Engine::EngineTimeout) engine duplication ran for 900 seconds

### ISSUE THREAD

**Issue by Disha-Shah** [codeclimate/codeclimate-duplication#120]
Whenever I run duplication engine, I ran into the following problem. 

.codeclimate.yml:
```
 duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript

```

Error : 

> error: (CC::Analyzer::Engine::EngineTimeout) engine duplication ran for 900 seconds and was killed

Please help. How can I increase timeout ?

**Comment by mrb** [comment]
@Disha-Shah There's another strategy besides increasing the timeout: analyzing fewer files. Have you excluded any files which are irrelevant to analysis? In the example above, there are no excludes. The duplication engine analyses all of your source code for duplications, so each extra file has quite an impact on the whole run. If your repo is open source, we can also make some suggestions there.

**Comment by aalaap** [comment]
I have the same problem even after excluding third-party files and other things in my Symfony project:

```
exclude_paths:
- "vendor/**/*"
- "vendor/*"
- "bin/**/*"
- "bin/*"
- "app/Resources/vendor/**/*"
- "app/Resources/vendor/*"
- "src/MyApp/AppBundle/Resources/public/js/bootstrap/**/*"
- "src/MyApp/AppBundle/Resources/public/js/jquery/*"
- "src/MyApp/AppBundle/Resources/public/js/external/*"
- "src/MyApp/AppBundle/Resources/public/img/**/*"
- "src/MyApp/AppBundle/Resources/public/img/*"
- "**/*Test.php"
- "**/jquery*"
- "**/modernizer*"
- "**/*.min.js"
- "**/bootstrap.js"
- "**/fg.menu.js"
```

What else do I exclude?

**Comment by dblandin** [comment]
Hey @Disha-Shah,

Generally an engine timeout hints at analyzing too many files or analyzing files that shouldn't be analyzed at all (minified files or other build artifacts).

You can however bump the timeout value while using the CLI by specifying a `CONTAINER_TIMEOUT_SECONDS` environment variable:

```
CONTAINER_TIMEOUT_SECONDS=1800 codeclimate analyze // 30 minutes
```

source: https://github.com/codeclimate/codeclimate/#environment-variables

**Comment by Enelar** [comment]
tried with one empty php file, got this issue

**Comment by zenspider** [comment]
@Enelar Can you show me your config and your output from:

```
CONTAINER_TIMEOUT_SECONDS=120 CODECLIMATE_DEBUG=1 codeclimate analyze
```

(feel free to make the timeout even shorter... an empty file is empty).

**Comment by tommyalvarez** [comment]
@zenspider In my case the issue is that I have hundres of lines like this:

```
D, [2019-05-21T17:13:26.816591 #1] DEBUG -- : engine stderr: 67ebd20cd36f: Pull complete
D, [2019-05-21T17:13:27.362720 #1] DEBUG -- : engine stderr: 9f3697f3d62b: Pull complete
D, [2019-05-21T17:13:28.297628 #1] DEBUG -- : engine stderr: c1384cea8670: Pull complete
D, [2019-05-21T17:13:30.553841 #1] DEBUG -- : engine stderr: 3488fd0267b4: Pull complete
D, [2019-05-21T17:13:31.378219 #1] DEBUG -- : engine stderr: ec44d80594a7: Pull complete
D, [2019-05-21T17:13:32.270406 #1] DEBUG -- : engine stderr: 17d2d797a561: Pull complete
D, [2019-05-21T17:13:33.349292 #1] DEBUG -- : engine stderr: 12fcbccfdcdb: Pull complete
D, [2019-05-21T17:13:33.802766 #1] DEBUG -- : engine stderr: d9e6b23b959f: Pull complete
D, [2019-05-21T17:13:36.237922 #1] DEBUG -- : engine stderr: ed5e4fb2fc23: Pull complete
D, [2019-05-21T17:13:37.297163 #1] DEBUG -- : engine stderr: 3a6010dc1b2e: Pull complete
D, [2019-05-21T17:13:38.950166 #1] DEBUG -- : engine stderr: cae6d4453ec8: Pull complete
D, [2019-05-21T17:13:39.368162 #1] DEBUG -- : engine stderr: 211ac35a0bb5: Pull complete
D, [2019-05-21T17:13:40.620090 #1] DEBUG -- : engine stderr: 3da534916919: Pull complete
D, [2019-05-21T17:13:41.074258 #1] DEBUG -- : engine stderr: cdb6d2f6681c: Pull complete
D, [2019-05-21T17:13:49.998417 #1] DEBUG -- : engine stderr: 2df99480a3b5: Pull complete
D, [2019-05-21T17:13:51.762473 #1] DEBUG -- : engine stderr: b5551034d9f7: Pull complete
D, [2019-05-21T17:14:41.704486 #1] DEBUG -- : engine stderr: e4bd778f32de: Pull complete
D, [2019-05-21T17:14:47.704823 #1] DEBUG -- : engine stderr: 9256ba1653ea: Pull complete
D, [2019-05-21T17:14:51.665901 #1] DEBUG -- : engine stderr: 412af1da999a: Pull complete
D, [2019-05-21T17:14:54.741061 #1] DEBUG -- : engine stderr: 04f0fe06687f: Pull complete
```

I think it's downloading something. But never finishes in timeout limit (Even with 1800s)

**Comment by zenspider** [comment]
Ouch... But, why not run the docker command to pull the image first?

This seems like a bootstrapping issue and has nothing to do with duplication other than being part of the bootstrap, no?

**Comment by tommyalvarez** [comment]
@zenspider because I didn't know about that command and I just ran `codeclimate analyze` haha. Good point

**Comment by zenspider** [comment]
Still seems like a @codeclimate bug to me... The timeout shouldn't apply until bootstrap is complete. Slower connections will never finish and throw away partial downloads.

@maxjacobson? Thoughts?

**Comment by amadeu01** [comment]
I guess we have to pull codeclimate-structure and codeclimate-duplication before trying to run the CI

**Comment by maxjacobson** [comment]
Hi!

The Code Climate CLI will run some docker containers to perform the code analysis. If the docker image isn't available, the CLI will pull it down, and then use it to run the container. I don't know off the top of my head whether the timeout is applying to the image pulling, but it sounds plausible to me. To help separate that out, you can first run this command to pull all of the necessary images:

```shell
codeclimate engines:install
```

Then, separately, you can run your `codeclimate analyze` invocation, and it won't need to pull any images.

Let me know if that helps address your concern.

**Comment by wfleming** [comment]
There's an issue on the CLI for this, fwiw: https://github.com/codeclimate/codeclimate/issues/866

**Comment by frakman1** [comment]
How do I disable the code duplication check? Is there something I can put in `.codeclimate.yml` or an environment variable to skip that?

**Comment by efueger** [comment]
Hi @frakman1. Yes!

You can disable:
- our newer (now default) **maintainability** duplication checks (similar and identical code) with [this](https://docs.codeclimate.com/docs/advanced-configuration#disabling-maintainability-checks)

```
version: "2"
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
```
- if you're using our older duplication engine/plugin directly, you'll use [this](https://github.com/codeclimate/codeclimate-duplication#codeclimate-duplication):

```
plugins:
  duplication:
    enabled: false
```

More on the difference between the 2 options [here](https://docs.codeclimate.com/docs/advanced-configuration#analysis-configuration-versions).
