### ISSUE TITLE
Using `beta` channel with JavaScript (ES6+) throws errors

### ISSUE THREAD

**Issue by rangoo94** [codeclimate/codeclimate-duplication#306]
I get errors inside of CodeClimate build during `duplication` process:

```
ERROR: couldn't find node type RestProperty in Sexp::NODE_NAMES.
ERROR: couldn't find node type SpreadProperty in Sexp::NODE_NAMES.
ERROR: couldn't find node type SpreadElement in Sexp::NODE_NAMES.
ERROR: couldn't find node type ClassExpression in Sexp::NODE_NAMES.
ERROR: couldn't find node type ForOfStatement in Sexp::NODE_NAMES.
ERROR: couldn't find node type AwaitExpression in Sexp::NODE_NAMES.
ERROR: couldn't find node type RestElement in Sexp::NODE_NAMES.
```

It seems that it doesn't know how to handle newer node types in JavaScript AST.

**Comment by wfleming** [comment]
Hi @rangoo94,

Sorry for the trouble. The `beta` channel is deprecated, and has not been updated in quite some time. It was created to give users the opportunity to test some new features, but wasn't intended to be used long-term. I'd suggest you please shift back to the `stable` (default) channel. Sorry that the communication around this deprecation missed you.

**Comment by wfleming** [comment]
I just read the comments on your `ui-kit` PR, and want to clarify that the changes that *were* being tested on the beta channel are on stable now, and other improvements since then as well.

**Comment by rangoo94** [comment]
Okay, thank you very much for the information, I tried `beta` channel, because of #89, where it's mentioned that it's working better on `beta` thanks to #190. I will close that ticket then, and I will look if there is a place for improvement in such situations.

Have a nice day!

**Comment by wfleming** [comment]
Ah, thank you for mentioning the ticket that pointed you towards beta. I'll take a look at that and update/close as appropriate.
