### ISSUE TITLE
unknown command engines:enable

### ISSUE THREAD

**Issue by toymachiner62** [codeclimate/codeclimate-duplication#336]
I just installed the codeclimate cli.

I followed the readme section https://github.com/codeclimate/codeclimate-duplication#installation
>Run codeclimate engines:enable duplication. This command installs the engine and enables it in your .codeclimate.yml file.

and I got the error:
```sh
$ codeclimate engines:enable duplication
unknown command engines:enable
```

**Comment by wfleming** [comment]
Thanks for the report, the README here is rather out of date in that regard. I've opened https://github.com/codeclimate/codeclimate-duplication/pull/337 to correct this.

Duplication analysis is enabled by default, so you don't need to do anything to enable it. You can run `codeclimate analyze` and it will run duplication analysis.

**Comment by wfleming** [comment]
#337 is merged, I'm going to close this, but let me know if there's any further issues here.
