### ISSUE TITLE
Question about hiding mass number

### ISSUE THREAD

**Issue by zeird** [codeclimate/codeclimate-duplication#50]
I use CC.com, enabled this engine with duplication functionality that I like a lot, and I couldn't find a mass numbers where they were on the old CC duplication analysis system (right next to an issue's title, in smaller text), and I thought that this wasn't implemented yet or a bug, but then I've found pull request #45 and concluded that mass numbers were removed on purpose.

So I have a question as a user:

> This makes the value accessible without unduly cluttering the description with that value.

Were there so many negative feedbacks about this thing, that @wfleming called it "unduly cluttering the description"? I mean, just look at the random screenshot with the result of this engine:

![](https://i.imgur.com/lFdy7Br.png)

What can I say about it as a user:

Every duplication issue's title has text in bold "**Similar code found in N other location(s)**", and actually it's rather (if not completely) useless now, because
* it's the only text duplication issues can have, and there's no way to list all issues, where it's title with "Similar code" text would be useful to distinguish duplication category issues from another;
* the meaningful info about a number of other locations is **duplicated** (oh, the irony) right there after the code block.
* at this point there's no easy way to at least estimate a mass of a chunk of code without additional actions, like
 * click on Read Up button (a mass is written there, ok, but how should I know that in the first place? I learned that only after finding that pull request I mentioned and hardly thinking about what "Read Up Contents" is, maybe that's because english is not my native language), then read a load of text just searching a number of mass: Blah-blah-blah-blah oh! the mass number!
 * click on "View more" button and then be frightened because an issue may be several screens long.

Why a user should know a mass in the first place? To determine severity of an issue, and it seems that before this pull-request this vital information wasn't even there!

So I want you to consider returning a mass number to issues titles or descriptions or anywhere where it could be found it without additional actions (like mouse clicks).

I guess for now I'll write a small userscript just for issues to look as they were before (with mass numbers, I mean).

Thanks for your attention, and for all the good you've brought to this world. :+1:

**Comment by GordonDiggs** [comment]
@zeird Thanks for the feedback! This is totally valid and we will work on improving this experience. Today, the remediation points of the issue are based on the [mass of the duplication itself](https://github.com/codeclimate/codeclimate-duplication/blob/master/lib/cc/engine/analyzers/violation.rb#L60). In other words, the bigger the block of duplication, the greater impact it will have on the grade of the file. I know this is not super transparent, but does at least help impact the way the issues are viewed.

It seems like there is an easy win in emitting the mass in the title of issue - I will see if we can make that happen.

**Comment by zeird** [comment]
> In other words, the bigger the block of duplication, the greater impact it will have on the grade of the file. I know this is not super transparent

Actually, this makes perfect sense. The bigger duplications there're, the less DRYed a code is. Nonetheless, I would like to see a mass number, not just to know how bad an issue affecting my grades, but to learn how much space is wasted (how much code is redundant) because of duplication.

**Comment by ABaldwinHunter** [comment]
@zeird Excellent news. Happy to report that we've [recently added the mass number](https://github.com/codeclimate/codeclimate-duplication/commit/c6165cd4d0bf3aec6290642a73f95a215d32297f) to a duplication issue's `description`. This information is visible in the UI of our hosted analysis and the CLI.

For more information, feel free to explore [our docs](https://docs.codeclimate.com/docs/duplication).

**Comment by ABaldwinHunter** [comment]
Closing this issue in light of recent updates.
