### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by adsteel** [codeclimate/codeclimate-duplication#51]
I've read through the readme and the codeclimate announcement. Still don't really know what this does, though I would assume it detects code duplication? Somehow? Could we add something to the readme that explains it?

**Comment by pbrisbin** [comment]
Hi @adsteel thanks for your question. While more information is always better, I think the README here and the [documentation](https://docs.codeclimate.com/docs/duplication) is sufficient enough for now.

Assuming someone understands Code Climate and engines in general, I believe the answer to what it does and how can be found via the short description and following the link to the Flay project itself:

> codeclimate-duplication is an engine that wraps **flay** and supports...

> Flay analyzes code for structural similarities. Differences in literal
> values, variable, class, method names, whitespace, programming style,
> braces vs do/end, etc are all ignored.

**Comment by adsteel** [comment]
Ah, I didn't catch that link to Flay initially. Thanks for pointing it out.
